# Generated by Django 5.2.3 on 2025-12-01 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0001_initial'),
        ('users', '0003_alter_userbike_verification_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challan',
            name='payment_proof',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.websiteuser'),
        ),
    ]
