# Generated by Django 5.2.3 on 2025-11-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_bike_stolen_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbike',
            name='verification_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Verified', max_length=20),
        ),
        migrations.AlterField(
            model_name='websiteuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
