# Generated by Django 5.2.3 on 2025-11-30 15:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=100)),
                ('sub_area', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('Constable', 'Constable'), ('Head Constable', 'Head Constable'), ('ASI', 'ASI'), ('SI', 'SI'), ('Inspector', 'Inspector')], max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('profile_pic_url', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Leave', 'Leave'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='officer.area')),
            ],
        ),
    ]
