# Generated by Django 5.2.3 on 2025-11-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='plain_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
